### ISSUE TITLE
Running production on Windows

### ISSUE THREAD

**Issue by rameshjesswani** [frab/frab#400]
I am following steps of installation from this link : https://github-cors.now.sh/afics/frab

First I installed ``development environment``, it works perfect. 
Now, since I am interested to export/import data of conferences, therefore, I am trying to install ``production environment`` . I followed steps from above link: These are commands that I executed:

``bundle install --without="postgresql mysql" ``

``cp config/database.yml.template config/database.yml `` ( i dont know, what to modify as it suggest in steps)

copy ``env. example`` and rename it to ``.env.production``

``rake assets:precompile``

For time being, I do not follow step 5 completely, but I only did ``Add a gem like exception_notification to get emails in case of errors``

`` RACK_ENV=production bundle rails s `` start the run for frab

Error: 
```
'RACK_ENV' is not recognized as an internal or external command,
operable program or batch file.
```

System Configuration:
Windows 7
ruby 2.4.3p205 (2017-12-14 revision 61247) [i386-mingw32]
nodejs version : 9.3.0
rails version: 5.1.4

Thanks in advance
Your help will be appreciated.

**Comment by rameshjesswani** [comment]
@manno could you please help me with this?

**Comment by manno** [comment]
@rameshjesswani `RACK_ENV` is an environment variable. You somehow have to set it in your Windows console? 
Try it in two separate lines?

```
set RACK_ENV=production
bundle exec rails s
```

**Comment by rameshjesswani** [comment]
@manno  thanks for your response

I am explaining you, what exactly I am trying to do. 

Idea is to export data of conference from frab into xml format. 

First, I generated fake data in development mode. Now, I want to export it. For this, I need to use production mode and then execute export command `` RAILS_ENV=production CONFERENCE=acronym rake frab:conference_export``

I executed these two commands separately

`` set RACK_ENV=production
bundle exec rails s
``

Now, I am not getting any error on command prompt. But when I try to check on ``localhost:3000``

It shows: 
```

We're sorry, but something went wrong.
We've been notified about this issue and we'll take a look at it shortly.

```

**Comment by manno** [comment]
There should be a more verbose error in the `log/production.log` file.

**Comment by rameshjesswani** [comment]
This is inside log/production.log 

` ` `
I, [2018-02-07T13:31:06.874876 #6520]  INFO -- : [c0bd665d-bdcb-4398-9069-cf028b38cc95] Started GET "/de/conferences?conference_acronym=siren-thirteen" for 127.0.0.1 at 2018-02-07 13:31:06 +0100
I, [2018-02-07T13:31:06.922880 #6520]  INFO -- : [c0bd665d-bdcb-4398-9069-cf028b38cc95] Processing by ConferencesController#index as HTML
I, [2018-02-07T13:31:06.923880 #6520]  INFO -- : [c0bd665d-bdcb-4398-9069-cf028b38cc95]   Parameters: {"conference_acronym"=>"siren-thirteen", "locale"=>"de"}
I, [2018-02-07T13:31:06.934882 #6520]  INFO -- : [c0bd665d-bdcb-4398-9069-cf028b38cc95] Completed 401 Unauthorized in 11ms
I, [2018-02-07T13:31:08.083996 #6520]  INFO -- : [e9ea5c0d-6904-4984-8a9b-96f7dd3aacf8] Started GET "/users/sign_in" for 127.0.0.1 at 2018-02-07 13:31:08 +0100
I, [2018-02-07T13:31:08.085997 #6520]  INFO -- : [e9ea5c0d-6904-4984-8a9b-96f7dd3aacf8] Processing by Auth::SessionsController#new as HTML
I, [2018-02-07T13:31:08.095998 #6520]  INFO -- : [e9ea5c0d-6904-4984-8a9b-96f7dd3aacf8] Completed 401 Unauthorized in 10ms (ActiveRecord: 0.0ms)
F, [2018-02-07T13:31:08.096998 #6520] FATAL -- : [e9ea5c0d-6904-4984-8a9b-96f7dd3aacf8]   
F, [2018-02-07T13:31:08.096998 #6520] FATAL -- : [e9ea5c0d-6904-4984-8a9b-96f7dd3aacf8] ActiveRecord::StatementInvalid (Could not find table 'users'):
F, [2018-02-07T13:31:08.096998 #6520] FATAL -- : [e9ea5c0d-6904-4984-8a9b-96f7dd3aacf8]   
F, [2018-02-07T13:31:08.096998 #6520] FATAL -- : [e9ea5c0d-6904-4984-8a9b-96f7dd3aacf8] activerecord (5.1.4) lib/active_record/connection_adapters/sqlite3_adapter.rb:417:in `table_structure'
[e9ea5c0d-6904-4984-8a9b-96f7dd3aacf8] activerecord (5.1.4) lib/active_record/connection_adapters/abstract_adapter.rb:166:in `columns'
[e9ea5c0d-6904-4984-8a9b-96f7dd3aacf8] activerecord (5.1.4) lib/active_record/connection_adapters/schema_cache.rb:67:in `columns'
[e9ea5c0d-6904-4984-8a9b-96f7dd3aacf8] activerecord (5.1.4) lib/active_record/connection_adapters/schema_cache.rb:73:in `columns_hash'
[e9ea5c0d-6904-4984-8a9b-96f7dd3aacf8] activerecord (5.1.4) lib/active_record/model_schema.rb:471:in `load_schema!'
[e9ea5c0d-6904-4984-8a9b-96f7dd3aacf8] activerecord (5.1.4) lib/active_record/attributes.rb:233:in `load_schema!'
[e9ea5c0d-6904-4984-8a9b-96f7dd3aacf8] activerecord (5.1.4) lib/active_record/attribute_decorators.rb:50:in `load_schema!'
[e9ea5c0d-6904-4984-8a9b-96f7dd3aacf8] activerecord (5.1.4) lib/active_record/model_schema.rb:464:in `block in load_schema'
[e9ea5c0d-6904-4984-8a9b-96f7dd3aacf8] C:/Ruby24/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
[e9ea5c0d-6904-4984-8a9b-96f7dd3aacf8] activerecord (5.1.4) lib/active_record/model_schema.rb:461:in `load_schema'
[e9ea5c0d-6904-4984-8a9b-96f7dd3aacf8] activerecord (5.1.4) lib/active_record/model_schema.rb:353:in `attribute_types'
[e9ea5c0d-6904-4984-8a9b-96f7dd3aacf8] activerecord (5.1.4) lib/active_record/attribute_methods.rb:179:in `has_attribute?'
[e9ea5c0d-6904-4984-8a9b-96f7dd3aacf8] activerecord (5.1.4) lib/active_record/inheritance.rb:55:in `new'
[e9ea5c0d-6904-4984-8a9b-96f7dd3aacf8] devise (4.4.0) app/controllers/devise/sessions_controller.rb:11:in `new'
[e9ea5c0d-6904-4984-8a9b-96f7dd3aacf8] actionpack (5.1.4) lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
[e9ea5c0d-6904-4984-8a9b-96f7dd3aacf8] actionpack (5.1.4) lib/abstract_controller/base.rb:186:in `process_action'
[e9ea5c0d-6904-4984-8a9b-96f7dd3aacf8] actionpack (5.1.4) lib/action_controller/metal/rendering.rb:30:in `process_action'
[e9ea5c0d-6904-4984-8a9b-96f7dd3aacf8] actionpack (5.1.4) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
[e9ea5c0d-6904-4984-8a9b-96f7dd3aacf8] activesupport (5.1.4) lib/active_support/callbacks.rb:131:in `run_callbacks'
[e9ea5c0d-6904-4984-8a9b-96f7dd3aacf8] actionpack (5.1.4) lib/abstract_controller/callbacks.rb:19:in `process_action'
[e9ea5c0d-6904-4984-8a9b-96f7dd3aacf8] actionpack (5.1.4) lib/action_controller/metal/rescue.rb:20:in `process_action'
[e9ea5c0d-6904-4984-8a9b-96f7dd3aacf8] actionpack (5.1.4) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
[e9ea5c0d-6904-4984-8a9b-96f7dd3aacf8] activesupport (5.1.4) lib/active_support/notifications.rb:166:in `block in instrument'
[e9ea5c0d-6904-4984-8a9b-96f7dd3aacf8] activesupport (5.1.4) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
[e9ea5c0d-6904-4984-8a9b-96f7dd3aacf8] activesupport (5.1.4) lib/active_support/notifications.rb:166:in `instrument'
[e9ea5c0d-6904-4984-8a9b-96f7dd3aacf8] actionpack (5.1.4) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
[e9ea5c0d-6904-4984-8a9b-96f7dd3aacf8] actionpack (5.1.4) lib/action_controller/metal/params_wrapper.rb:252:in `process_action'
[e9ea5c0d-6904-4984-8a9b-96f7dd3aacf8] activerecord (5.1.4) lib/active_record/railties/controller_runtime.rb:22:in `process_action'
[e9ea5c0d-6904-4984-8a9b-96f7dd3aacf8] actionpack (5.1.4) lib/abstract_controller/base.rb:124:in `process'
[e9ea5c0d-6904-4984-8a9b-96f7dd3aacf8] actionview (5.1.4) lib/action_view/rendering.rb:30:in `process'
[e9ea5c0d-6904-4984-8a9b-96f7dd3aacf8] actionpack (5.1.4) lib/action_controller/metal.rb:189:in `dispatch'
[e9ea5c0d-6904-4984-8a9b-96f7dd3aacf8] actionpack (5.1.4) lib/action_controller/metal.rb:253:in `dispatch'
[e9ea5c0d-6904-4984-8a9b-96f7dd3aacf8] actionpack (5.1.4) lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
[e9ea5c0d-6904-4984-8a9b-96f7dd3aacf8] actionpack (5.1.4) lib/action_dispatch/routing/route_set.rb:31:in `serve'
[e9ea5c0d-6904-4984-8a9b-96f7dd3aacf8] actionpack (5.1.4) lib/action_dispatch/routing/mapper.rb:16:in `block in <class:Constraints>'
[e9ea5c0d-6904-4984-8a9b-96f7dd3aacf8] actionpack (5.1.4) lib/action_dispatch/routing/mapper.rb:46:in `serve'
[e9ea5c0d-6904-4984-8a9b-96f7dd3aacf8] actionpack (5.1.4) lib/action_dispatch/journey/router.rb:50:in `block in serve'
[e9ea5c0d-6904-4984-8a9b-96f7dd3aacf8] actionpack (5.1.4) lib/action_dispatch/journey/router.rb:33:in `each'
[e9ea5c0d-6904-4984-8a9b-96f7dd3aacf8] actionpack (5.1.4) lib/action_dispatch/journey/router.rb:33:in `serve'
[e9ea5c0d-6904-4984-8a9b-96f7dd3aacf8] actionpack (5.1.4) lib/action_dispatch/routing/route_set.rb:834:in `call'
[e9ea5c0d-6904-4984-8a9b-96f7dd3aacf8] http_accept_language (2.1.1) lib/http_accept_language/middleware.rb:14:in `call'
[e9ea5c0d-6904-4984-8a9b-96f7dd3aacf8] warden (1.2.7) lib/warden/manager.rb:36:in `block in call'
[e9ea5c0d-6904-4984-8a9b-96f7dd3aacf8] warden (1.2.7) lib/warden/manager.rb:35:in `catch'
[e9ea5c0d-6904-4984-8a9b-96f7dd3aacf8] warden (1.2.7) lib/warden/manager.rb:35:in `call'
[e9ea5c0d-6904-4984-8a9b-96f7dd3aacf8] rack (2.0.3) lib/rack/etag.rb:25:in `call'
[e9ea5c0d-6904-4984-8a9b-96f7dd3aacf8] rack (2.0.3) lib/rack/conditional_get.rb:25:in `call'
[e9ea5c0d-6904-4984-8a9b-96f7dd3aacf8] rack (2.0.3) lib/rack/head.rb:12:in `call'
[e9ea5c0d-6904-4984-8a9b-96f7dd3aacf8] rack (2.0.3) lib/rack/session/abstract/id.rb:232:in `context'
[e9ea5c0d-6904-4984-8a9b-96f7dd3aacf8] rack (2.0.3) lib/rack/session/abstract/id.rb:226:in `call'
[e9ea5c0d-6904-4984-8a9b-96f7dd3aacf8] actionpack (5.1.4) lib/action_dispatch/middleware/cookies.rb:613:in `call'
[e9ea5c0d-6904-4984-8a9b-96f7dd3aacf8] actionpack (5.1.4) lib/action_dispatch/middleware/callbacks.rb:26:in `block in call'
[e9ea5c0d-6904-4984-8a9b-96f7dd3aacf8] activesupport (5.1.4) lib/active_support/callbacks.rb:97:in `run_callbacks'
[e9ea5c0d-6904-4984-8a9b-96f7dd3aacf8] actionpack (5.1.4) lib/action_dispatch/middleware/callbacks.rb:24:in `call'
[e9ea5c0d-6904-4984-8a9b-96f7dd3aacf8] actionpack (5.1.4) lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call'
[e9ea5c0d-6904-4984-8a9b-96f7dd3aacf8] actionpack (5.1.4) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
[e9ea5c0d-6904-4984-8a9b-96f7dd3aacf8] railties (5.1.4) lib/rails/rack/logger.rb:36:in `call_app'
[e9ea5c0d-6904-4984-8a9b-96f7dd3aacf8] railties (5.1.4) lib/rails/rack/logger.rb:24:in `block in call'
[e9ea5c0d-6904-4984-8a9b-96f7dd3aacf8] activesupport (5.1.4) lib/active_support/tagged_logging.rb:69:in `block in tagged'
[e9ea5c0d-6904-4984-8a9b-96f7dd3aacf8] activesupport (5.1.4) lib/active_support/tagged_logging.rb:26:in `tagged'
[e9ea5c0d-6904-4984-8a9b-96f7dd3aacf8] activesupport (5.1.4) lib/active_support/tagged_logging.rb:69:in `tagged'
[e9ea5c0d-6904-4984-8a9b-96f7dd3aacf8] railties (5.1.4) lib/rails/rack/logger.rb:24:in `call'
[e9ea5c0d-6904-4984-8a9b-96f7dd3aacf8] actionpack (5.1.4) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
[e9ea5c0d-6904-4984-8a9b-96f7dd3aacf8] request_store (1.4.0) lib/request_store/middleware.rb:19:in `call'
[e9ea5c0d-6904-4984-8a9b-96f7dd3aacf8] actionpack (5.1.4) lib/action_dispatch/middleware/request_id.rb:25:in `call'
[e9ea5c0d-6904-4984-8a9b-96f7dd3aacf8] rack (2.0.3) lib/rack/method_override.rb:22:in `call'
[e9ea5c0d-6904-4984-8a9b-96f7dd3aacf8] rack (2.0.3) lib/rack/runtime.rb:22:in `call'
[e9ea5c0d-6904-4984-8a9b-96f7dd3aacf8] activesupport (5.1.4) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
[e9ea5c0d-6904-4984-8a9b-96f7dd3aacf8] actionpack (5.1.4) lib/action_dispatch/middleware/executor.rb:12:in `call'
[e9ea5c0d-6904-4984-8a9b-96f7dd3aacf8] rack (2.0.3) lib/rack/sendfile.rb:111:in `call'
[e9ea5c0d-6904-4984-8a9b-96f7dd3aacf8] railties (5.1.4) lib/rails/engine.rb:522:in `call'
[e9ea5c0d-6904-4984-8a9b-96f7dd3aacf8] puma (3.11.0) lib/puma/configuration.rb:225:in `call'
[e9ea5c0d-6904-4984-8a9b-96f7dd3aacf8] puma (3.11.0) lib/puma/server.rb:624:in `handle_request'
[e9ea5c0d-6904-4984-8a9b-96f7dd3aacf8] puma (3.11.0) lib/puma/server.rb:438:in `process_client'
[e9ea5c0d-6904-4984-8a9b-96f7dd3aacf8] puma (3.11.0) lib/puma/server.rb:302:in `block in run'
[e9ea5c0d-6904-4984-8a9b-96f7dd3aacf8] puma (3.11.0) lib/puma/thread_pool.rb:120:in `block in spawn_thread'
I, [2018-02-07T13:31:18.373025 #6520]  INFO -- : [692a08d2-4957-4c5a-836c-3b0c587f71d3] Started GET "/" for 127.0.0.1 at 2018-02-07 13:31:18 +0100
I, [2018-02-07T13:31:18.375025 #6520]  INFO -- : [692a08d2-4957-4c5a-836c-3b0c587f71d3] Processing by HomeController#index as HTML
I, [2018-02-07T13:31:18.479036 #6520]  INFO -- : [692a08d2-4957-4c5a-836c-3b0c587f71d3]   Rendering home/index.html.haml within layouts/application
I, [2018-02-07T13:31:18.518040 #6520]  INFO -- : [692a08d2-4957-4c5a-836c-3b0c587f71d3]   Rendered home/index.html.haml within layouts/application (39.0ms)
I, [2018-02-07T13:31:18.519040 #6520]  INFO -- : [692a08d2-4957-4c5a-836c-3b0c587f71d3] Completed 401 Unauthorized in 144ms (ActiveRecord: 0.0ms)
F, [2018-02-07T13:31:18.519040 #6520] FATAL -- : [692a08d2-4957-4c5a-836c-3b0c587f71d3]   
F, [2018-02-07T13:31:18.520040 #6520] FATAL -- : [692a08d2-4957-4c5a-836c-3b0c587f71d3] ActionView::Template::Error (Could not find table 'conferences'):
F, [2018-02-07T13:31:18.520040 #6520] FATAL -- : [692a08d2-4957-4c5a-836c-3b0c587f71d3]     15:     %li{class: active_class?(root_path)}= link_to t('conferences_module.current_conferences'), root_path
[692a08d2-4957-4c5a-836c-3b0c587f71d3]     16:     %li{class: active_class?(past_conferences_path)}= link_to t('conferences_module.past_conferences'), past_conferences_path
[692a08d2-4957-4c5a-836c-3b0c587f71d3]     17: 
[692a08d2-4957-4c5a-836c-3b0c587f71d3]     18:   - if Conference.all.empty?
[692a08d2-4957-4c5a-836c-3b0c587f71d3]     19:     .row
[692a08d2-4957-4c5a-836c-3b0c587f71d3]     20:       .span16
[692a08d2-4957-4c5a-836c-3b0c587f71d3]     21:         .blank-slate{style: 'padding-bottom: 33%'}
F, [2018-02-07T13:31:18.520040 #6520] FATAL -- : [692a08d2-4957-4c5a-836c-3b0c587f71d3]   
F, [2018-02-07T13:31:18.520040 #6520] FATAL -- : [692a08d2-4957-4c5a-836c-3b0c587f71d3] app/views/home/index.html.haml:18:in `_app_views_home_index_html_haml___294656931_63153660'

` ` `

**Comment by manno** [comment]
No idea, closing for inactivity. Windows is not a supported platform.
