### ISSUE TITLE
undefined method `review_metrics' when rake frab:conference_export

### ISSUE THREAD

**Issue by pcfe** [frab/frab#598]
### disclaimer, noob frab user
I started looking into frab only 2 days ago and I know little to no Ruby, so I may very well be doing something wrong. 

## description of problem
Trying to backup I run into 
```
undefined method `review_metrics' for #<Conference…
```

## steps to reproduce
1. install frab (container deployment)
2. create a test conference
3. add days
4. add events, set as 'scheduled' (simply because it was a first test)
5. do not test submission grading yet
6. try to backup with `RAILS_ENV=production CONFERENCE=acronym rake frab:conference_export`

## actual result
```
pcfe@karhu frab (pcfe-testing-201911) $ oc rsh frab-68-wx9qn 
$ bash
frab@frab-68-wx9qn:~/app$ . .env.production 
frab@frab-68-wx9qn:~/app$ RAILS_ENV=production CONFERENCE=desm201911 rake frab:conference_export --trace
** Invoke frab:conference_export (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute frab:conference_export
rake aborted!
NoMethodError: undefined method `review_metrics' for #<Conference:0x000055a656d12fc0>
/usr/local/bundle/gems/activemodel-5.2.2.1/lib/active_model/attribute_methods.rb:430:in `method_missing'
/home/frab/app/app/lib/import_export_helper.rb:27:in `block in run_export'
/usr/local/bundle/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:259:in `block in transaction'
/usr/local/bundle/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/abstract/transaction.rb:239:in `block in within_new_transaction'
/usr/local/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
/usr/local/bundle/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/abstract/transaction.rb:236:in `within_new_transaction'
/usr/local/bundle/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:259:in `transaction'
/usr/local/bundle/gems/activerecord-5.2.2.1/lib/active_record/transactions.rb:212:in `transaction'
/home/frab/app/app/lib/import_export_helper.rb:20:in `run_export'
/home/frab/app/lib/tasks/frab_import_export.rake:12:in `block (2 levels) in <main>'
/usr/local/bundle/gems/rake-13.0.0/lib/rake/task.rb:280:in `block in execute'
/usr/local/bundle/gems/rake-13.0.0/lib/rake/task.rb:280:in `each'
/usr/local/bundle/gems/rake-13.0.0/lib/rake/task.rb:280:in `execute'
/usr/local/bundle/gems/rake-13.0.0/lib/rake/task.rb:218:in `block in invoke_with_call_chain'
/usr/local/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
/usr/local/bundle/gems/rake-13.0.0/lib/rake/task.rb:198:in `invoke_with_call_chain'
/usr/local/bundle/gems/rake-13.0.0/lib/rake/task.rb:187:in `invoke'
/usr/local/bundle/gems/rake-13.0.0/lib/rake/application.rb:160:in `invoke_task'
/usr/local/bundle/gems/rake-13.0.0/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/usr/local/bundle/gems/rake-13.0.0/lib/rake/application.rb:116:in `each'
/usr/local/bundle/gems/rake-13.0.0/lib/rake/application.rb:116:in `block in top_level'
/usr/local/bundle/gems/rake-13.0.0/lib/rake/application.rb:125:in `run_with_threads'
/usr/local/bundle/gems/rake-13.0.0/lib/rake/application.rb:110:in `top_level'
/usr/local/bundle/gems/rake-13.0.0/lib/rake/application.rb:83:in `block in run'
/usr/local/bundle/gems/rake-13.0.0/lib/rake/application.rb:186:in `standard_exception_handling'
/usr/local/bundle/gems/rake-13.0.0/lib/rake/application.rb:80:in `run'
/usr/local/bundle/gems/rake-13.0.0/exe/rake:27:in `<top (required)>'
/usr/local/bundle/bin/rake:23:in `load'
/usr/local/bundle/bin/rake:23:in `<main>'
Tasks: TOP => frab:conference_export
frab@frab-68-wx9qn:~/app$
```

## expected result
export written to `tmp/frab_export`

## additional info
if I revert 658c7effb8be548422424ce3f7f16f4e3663d744, then I can create an export just fine
(which I then pull off the pod with `oc rsync`)

**Comment by eladeyal-intel** [comment]
Review metrics were not merged yet. It's in https://github.com/frab/frab/pull/557. I think I could have created the PR with a better sense of order.

**Comment by eladeyal-intel** [comment]
#557 was merged.
I checked `frab:conference_export` `frab:conference_import` and now they seem fine.
I recommend to close this ticket.

**Comment by pcfe** [comment]
while frab:conference_export works for me now with review_metrics, restoring an older backup failed with the below.

But I'll have to test a few more things to be sure it's not me before opening an issue for that.

```
I have no name!@frab-104-xhwdh:~$ RAILS_ENV=production rake frab:conference_import                                                                                                                                                             
[ ] restore conference                                                                                                                                                                                                                         
    conference: DE Services Meeting Leipzig November 2019 (desm201911)                                                                                                                                                                         
[ ] restore all conference_tracks                                                                                                                                                                                                              
[ ] restore conference_cfp                                                                                                                                                                                                                     
[ ] restore conference_ticket_server                                                                                                                                                                                                           
[ ] restore all conference_rooms                                                                                                                                                                                                               
[ ] restore all conference_days                                                                                                                                                                                                                
[ ] restore all conference_languages                                                                                                                                                                                                           
[ ] restore all conference_review_metrics                                                                                                                                                                                                      
rake aborted!                                                                                                                                                                                                                                  
Errno::ENOENT: No such file or directory - bs_fetch:open_current_file:open                                                                                                                                                                     
/usr/local/bundle/gems/bootsnap-1.4.1/lib/bootsnap/compile_cache/yaml.rb:49:in `fetch'                                                                                                                                                         
/usr/local/bundle/gems/bootsnap-1.4.1/lib/bootsnap/compile_cache/yaml.rb:49:in `block in install!'                                                                                                                                             
/opt/frab/app/app/lib/import_export_helper.rb:321:in `restore_multiple'                                                                                                                                                                        
/opt/frab/app/app/lib/import_export_helper.rb:191:in `restore_conference_data'                                                                                                                                                                 
/opt/frab/app/app/lib/import_export_helper.rb:88:in `restore_all_data'                                                                                                                                                                         
/opt/frab/app/app/lib/import_export_helper.rb:69:in `block in run_import'                                                                                                                                                                      
/usr/local/bundle/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:259:in `block in transaction'                                                                                                
/usr/local/bundle/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/abstract/transaction.rb:239:in `block in within_new_transaction'                                                                                             
/usr/local/bundle/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/abstract/transaction.rb:236:in `within_new_transaction'                                                                                                      
/usr/local/bundle/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:259:in `transaction'                                                                                                         
/usr/local/bundle/gems/activerecord-5.2.2.1/lib/active_record/transactions.rb:212:in `transaction'                                                                                                                                             
/opt/frab/app/app/lib/import_export_helper.rb:67:in `run_import'                                                                                                                                                                               
/opt/frab/app/lib/tasks/frab_import_export.rake:23:in `block (2 levels) in <main>'                                                                                                                                                             
/usr/local/bundle/gems/rake-13.0.0/exe/rake:27:in `<top (required)>'                                                                                                                                                                           
Tasks: TOP => frab:conference_import                                                                                                                                                                                                           
(See full trace by running task with --trace)```

I could work around it by creating a conference 'foo', exporting that, rsyncing my old backup over the export directory and running import again.
