### ISSUE TITLE
db:migrate fails with master

### ISSUE THREAD

**Issue by erdgeist** [frab/frab#625]
== 20191002000000 AddAllowedEventTypesToConferences: migrating ================
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

SQLite3::SQLException: no such table: review_metrics: SELECT "review_metrics".* FROM "review_metrics"
/usr/home/erdgeist/.rvm/gems/ruby-2.4.5/gems/sqlite3-1.3.13/lib/sqlite3/database.rb:91:in `initialize'
/usr/home/erdgeist/.rvm/gems/ruby-2.4.5/gems/sqlite3-1.3.13/lib/sqlite3/database.rb:91:in `new'
/usr/home/erdgeist/.rvm/gems/ruby-2.4.5/gems/sqlite3-1.3.13/lib/sqlite3/database.rb:91:in `prepare'
/usr/home/erdgeist/.rvm/gems/ruby-2.4.5/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/sqlite3_adapter.rb:228:in `block (2 levels) in exec_query'

**Comment by erdgeist** [comment]
@eladeyal-intel Any idea why the 20191002000000 migration would even need review_metrics? That was only introduced on the next migration.

**Comment by erdgeist** [comment]
Hm, I reset the database and now all migrations apply in order. I hope no one in the wild encounters this. Losing the database is no fun.
