### ISSUE TITLE
cannot restore backup without conference_review_metrics to freshly installed version with #557 

### ISSUE THREAD

**Issue by pcfe** [frab/frab#642]
@eladeyal-intel
I have a backup that I created without *conference_review_metrics* (taken at the time of #598 ), when I try to restore that on a current frab version that is empty (so one where #557 and #549 are in), then I get

```bash
$ oc rsh frab-104-l9tr9
$ bash
I have no name!@frab-104-l9tr9:~$ . .env.production 
I have no name!@frab-104-l9tr9:~$ RAILS_ENV=production rake frab:conference_import --trace
** Invoke frab:conference_import (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute frab:conference_import
[ ] restore conference
    conference: [REDACTED]
[ ] restore all conference_tracks
[ ] restore conference_cfp
[ ] restore conference_ticket_server
[ ] restore all conference_rooms
[ ] restore all conference_days
[ ] restore all conference_languages
[ ] restore all conference_review_metrics
rake aborted!
Errno::ENOENT: No such file or directory - bs_fetch:open_current_file:open
/usr/local/bundle/gems/bootsnap-1.4.1/lib/bootsnap/compile_cache/yaml.rb:49:in `fetch'
/usr/local/bundle/gems/bootsnap-1.4.1/lib/bootsnap/compile_cache/yaml.rb:49:in `block in install!'
/opt/frab/app/app/lib/import_export_helper.rb:321:in `restore_multiple'
/opt/frab/app/app/lib/import_export_helper.rb:191:in `restore_conference_data'
/opt/frab/app/app/lib/import_export_helper.rb:88:in `restore_all_data'
/opt/frab/app/app/lib/import_export_helper.rb:69:in `block in run_import'
/usr/local/bundle/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:259:in `block in transaction'
/usr/local/bundle/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/abstract/transaction.rb:239:in `block in within_new_transaction'
/usr/local/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
/usr/local/bundle/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/abstract/transaction.rb:236:in `within_new_transaction'
/usr/local/bundle/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:259:in `transaction'
/usr/local/bundle/gems/activerecord-5.2.2.1/lib/active_record/transactions.rb:212:in `transaction'
/opt/frab/app/app/lib/import_export_helper.rb:67:in `run_import'
/opt/frab/app/lib/tasks/frab_import_export.rake:23:in `block (2 levels) in <main>'
/usr/local/bundle/gems/rake-13.0.0/lib/rake/task.rb:280:in `block in execute'
/usr/local/bundle/gems/rake-13.0.0/lib/rake/task.rb:280:in `each'
/usr/local/bundle/gems/rake-13.0.0/lib/rake/task.rb:280:in `execute'
/usr/local/bundle/gems/rake-13.0.0/lib/rake/task.rb:218:in `block in invoke_with_call_chain'
/usr/local/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
/usr/local/bundle/gems/rake-13.0.0/lib/rake/task.rb:198:in `invoke_with_call_chain'
/usr/local/bundle/gems/rake-13.0.0/lib/rake/task.rb:187:in `invoke'
/usr/local/bundle/gems/rake-13.0.0/lib/rake/application.rb:160:in `invoke_task'
/usr/local/bundle/gems/rake-13.0.0/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/usr/local/bundle/gems/rake-13.0.0/lib/rake/application.rb:116:in `each'
/usr/local/bundle/gems/rake-13.0.0/lib/rake/application.rb:116:in `block in top_level'
/usr/local/bundle/gems/rake-13.0.0/lib/rake/application.rb:125:in `run_with_threads'
/usr/local/bundle/gems/rake-13.0.0/lib/rake/application.rb:110:in `top_level'
/usr/local/bundle/gems/rake-13.0.0/lib/rake/application.rb:83:in `block in run'
/usr/local/bundle/gems/rake-13.0.0/lib/rake/application.rb:186:in `standard_exception_handling'
/usr/local/bundle/gems/rake-13.0.0/lib/rake/application.rb:80:in `run'
/usr/local/bundle/gems/rake-13.0.0/exe/rake:27:in `<top (required)>'
/usr/local/bundle/bin/rake:23:in `load'
/usr/local/bundle/bin/rake:23:in `<main>'
Tasks: TOP => frab:conference_import
```

Simply giving it two empty dump files (names taken from 658c7effb8be548422424ce3f7f16f4e3663d744 ) does not help.

```bash
I have no name!@frab-104-dvkws:~$ touch tmp/frab_export/conference_review_metrics.yml                                   
I have no name!@frab-104-dvkws:~$ touch tmp/frab_export/event_review_scores.yml      
I have no name!@frab-104-dvkws:~$ RAILS_ENV=production rake frab:conference_import --trace                              
** Invoke frab:conference_import (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute frab:conference_import
[ ] restore conference
    conference: [REDACTED]
[ ] restore all conference_tracks
[ ] restore conference_cfp
[ ] restore conference_ticket_server
[ ] restore all conference_rooms
[ ] restore all conference_days
[ ] restore all conference_languages
[ ] restore all conference_review_metrics
rake aborted!
Errno::ENOENT: No such file or directory - bs_fetch:open_current_file:open
/usr/local/bundle/gems/bootsnap-1.4.1/lib/bootsnap/compile_cache/yaml.rb:49:in `fetch'
/usr/local/bundle/gems/bootsnap-1.4.1/lib/bootsnap/compile_cache/yaml.rb:49:in `block in install!'
/opt/frab/app/app/lib/import_export_helper.rb:321:in `restore_multiple'
/opt/frab/app/app/lib/import_export_helper.rb:191:in `restore_conference_data'
/opt/frab/app/app/lib/import_export_helper.rb:88:in `restore_all_data'
/opt/frab/app/app/lib/import_export_helper.rb:69:in `block in run_import'
/usr/local/bundle/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:259:in `block in transaction'
/usr/local/bundle/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/abstract/transaction.rb:239:in `block in within_new_transaction'
/usr/local/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
/usr/local/bundle/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/abstract/transaction.rb:236:in `within_new_transaction'
/usr/local/bundle/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:259:in `transaction'
/usr/local/bundle/gems/activerecord-5.2.2.1/lib/active_record/transactions.rb:212:in `transaction'
/opt/frab/app/app/lib/import_export_helper.rb:67:in `run_import'
/opt/frab/app/lib/tasks/frab_import_export.rake:23:in `block (2 levels) in <main>'
/usr/local/bundle/gems/rake-13.0.0/lib/rake/task.rb:280:in `block in execute'
/usr/local/bundle/gems/rake-13.0.0/lib/rake/task.rb:280:in `each'
/usr/local/bundle/gems/rake-13.0.0/lib/rake/task.rb:280:in `execute'
/usr/local/bundle/gems/rake-13.0.0/lib/rake/task.rb:218:in `block in invoke_with_call_chain'
/usr/local/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
/usr/local/bundle/gems/rake-13.0.0/lib/rake/task.rb:198:in `invoke_with_call_chain'
/usr/local/bundle/gems/rake-13.0.0/lib/rake/task.rb:187:in `invoke'
/usr/local/bundle/gems/rake-13.0.0/lib/rake/application.rb:160:in `invoke_task'
/usr/local/bundle/gems/rake-13.0.0/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/usr/local/bundle/gems/rake-13.0.0/lib/rake/application.rb:116:in `each'
/usr/local/bundle/gems/rake-13.0.0/lib/rake/application.rb:116:in `block in top_level'
/usr/local/bundle/gems/rake-13.0.0/lib/rake/application.rb:125:in `run_with_threads'
/usr/local/bundle/gems/rake-13.0.0/lib/rake/application.rb:110:in `top_level'
/usr/local/bundle/gems/rake-13.0.0/lib/rake/application.rb:83:in `block in run'
/usr/local/bundle/gems/rake-13.0.0/lib/rake/application.rb:186:in `standard_exception_handling'
/usr/local/bundle/gems/rake-13.0.0/lib/rake/application.rb:80:in `run'
/usr/local/bundle/gems/rake-13.0.0/exe/rake:27:in `<top (required)>'
/usr/local/bundle/bin/rake:23:in `load'
/usr/local/bundle/bin/rake:23:in `<main>'
Tasks: TOP => frab:conference_import
I have no name!@frab-104-dvkws:~$ command terminated with exit code 137
```

giving them a file with
```
--- []
```

also does not help;
```bash
$ oc rsh frab-104-l9tr9 
$ bash
I have no name!@frab-104-l9tr9:~$ . .env.production 
I have no name!@frab-104-l9tr9:~$ cp tmp/frab_export/event_links.yaml tmp/frab_export/conference_review_metrics.yml
I have no name!@frab-104-l9tr9:~$ cp tmp/frab_export/event_links.yaml tmp/frab_export/event_review_scores.yml      
I have no name!@frab-104-l9tr9:~$ RAILS_ENV=production rake frab:conference_import --trace 
** Invoke frab:conference_import (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute frab:conference_import
[ ] restore conference
    conference: [REDACTED]
[ ] restore all conference_tracks
[ ] restore conference_cfp
[ ] restore conference_ticket_server
[ ] restore all conference_rooms
[ ] restore all conference_days
[ ] restore all conference_languages
[ ] restore all conference_review_metrics
rake aborted!
Errno::ENOENT: No such file or directory - bs_fetch:open_current_file:open
/usr/local/bundle/gems/bootsnap-1.4.1/lib/bootsnap/compile_cache/yaml.rb:49:in `fetch'
/usr/local/bundle/gems/bootsnap-1.4.1/lib/bootsnap/compile_cache/yaml.rb:49:in `block in install!'
/opt/frab/app/app/lib/import_export_helper.rb:321:in `restore_multiple'
/opt/frab/app/app/lib/import_export_helper.rb:191:in `restore_conference_data'
/opt/frab/app/app/lib/import_export_helper.rb:88:in `restore_all_data'
/opt/frab/app/app/lib/import_export_helper.rb:69:in `block in run_import'
/usr/local/bundle/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:259:in `block in transaction'
/usr/local/bundle/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/abstract/transaction.rb:239:in `block in within_new_transaction'
/usr/local/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
/usr/local/bundle/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/abstract/transaction.rb:236:in `within_new_transaction'
/usr/local/bundle/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:259:in `transaction'
/usr/local/bundle/gems/activerecord-5.2.2.1/lib/active_record/transactions.rb:212:in `transaction'
/opt/frab/app/app/lib/import_export_helper.rb:67:in `run_import'
/opt/frab/app/lib/tasks/frab_import_export.rake:23:in `block (2 levels) in <main>'
/usr/local/bundle/gems/rake-13.0.0/lib/rake/task.rb:280:in `block in execute'
/usr/local/bundle/gems/rake-13.0.0/lib/rake/task.rb:280:in `each'
/usr/local/bundle/gems/rake-13.0.0/lib/rake/task.rb:280:in `execute'
/usr/local/bundle/gems/rake-13.0.0/lib/rake/task.rb:218:in `block in invoke_with_call_chain'
/usr/local/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
/usr/local/bundle/gems/rake-13.0.0/lib/rake/task.rb:198:in `invoke_with_call_chain'
/usr/local/bundle/gems/rake-13.0.0/lib/rake/task.rb:187:in `invoke'
/usr/local/bundle/gems/rake-13.0.0/lib/rake/application.rb:160:in `invoke_task'
/usr/local/bundle/gems/rake-13.0.0/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/usr/local/bundle/gems/rake-13.0.0/lib/rake/application.rb:116:in `each'
/usr/local/bundle/gems/rake-13.0.0/lib/rake/application.rb:116:in `block in top_level'
/usr/local/bundle/gems/rake-13.0.0/lib/rake/application.rb:125:in `run_with_threads'
/usr/local/bundle/gems/rake-13.0.0/lib/rake/application.rb:110:in `top_level'
/usr/local/bundle/gems/rake-13.0.0/lib/rake/application.rb:83:in `block in run'
/usr/local/bundle/gems/rake-13.0.0/lib/rake/application.rb:186:in `standard_exception_handling'
/usr/local/bundle/gems/rake-13.0.0/lib/rake/application.rb:80:in `run'
/usr/local/bundle/gems/rake-13.0.0/exe/rake:27:in `<top (required)>'
/usr/local/bundle/bin/rake:23:in `load'
/usr/local/bundle/bin/rake:23:in `<main>'
Tasks: TOP => frab:conference_import
I have no name!@frab-104-l9tr9:~$ cat tmp/frab_export/event_review_scores.yml
--- []
I have no name!@frab-104-l9tr9:~$ cat tmp/frab_export/conference_review_metrics.yml 
--- []
```

**Comment by eladeyal-intel** [comment]
The filename extension should be `yaml` and not `yml`. The content `--- []` should work.

**Comment by pcfe** [comment]
Thanks. `yaml` extension makes import work.
But then the server throws 500s (see one pasted below)

```bash
$ oc rsh frab-116-xdftv                                                                                                                                                                               
$ bash                                                                                                                                                                                                                                         
I have no name!@frab-116-xdftv:~$ . .env.production                                                                                                                                                                                            
I have no name!@frab-116-xdftv:~$ cp tmp/frab_export/event_links.yaml tmp/frab_export/conference_review_metrics.yaml                                                                                                                           
I have no name!@frab-116-xdftv:~$ cp tmp/frab_export/event_links.yaml tmp/frab_export/event_review_scores.yaml                                                                                                                                 
I have no name!@frab-116-xdftv:~$ RAILS_ENV=production rake frab:conference_import                                                                                                                                                             
[ ] restore conference                                                                                                                                                                                                                         
    conference: [REDACTED]                                                                                                                                                                         
[ ] restore all conference_tracks                                                                                                                                                                                                              
[ ] restore conference_cfp                                                                                                                                                                                                                     
[ ] restore conference_ticket_server                                                                                                                                                                                                           
[ ] restore all conference_rooms                                                                                                                                                                                                               
[ ] restore all conference_days                                                                                                                                                                                                                
[ ] restore all conference_languages                                                                                                                                                                                                           
[ ] restore all conference_review_metrics                                                                                                                                                                                                      
[ ] restore all people                                                                                                                                                                                                                         
[ ] restore all users                                                                                                                                                                                                                          
[ ] restore all events                                                                                                                                                                                                                         
[ ] restore all tickets                                                                                                                                                                                                                        
[ ] restore all event_people                                                                                                                                                                                                                   
[ ] restore all event_feedbacks                                                                                                                                                                                                                
[ ] restore all event_ratings                                                                                                                                                                                                                  
[ ] restore all event_review_scores                                                                                                                                                                                                            
[ ] restore all event_links                                                                                                                                                                                                                    
[ ] restore all event_attachments                                                                                                                                                                                                              
[ ] restore all people_phone_numbers                                                                                                                                                                                                           
[ ] restore all people_im_accounts                                                                                                                                                                                                             
[ ] restore all people_links                                                                                                                                                                                                                   
[ ] restore all people_languages                                                                                                                                                                                                               
[ ] restore all people_availabilities
I have no name!@frab-116-xdftv:~$ 
```

```
I, [2019-11-10T22:03:20.264608 #101]  INFO -- : [6190d2d9-eaa8-4ca8-a1f8-f8ec22cd2c08] Started GET "/" for 10.130.0.1 at 2019-11-10 22:03:20 +0100                                                                                             
I, [2019-11-10T22:03:20.266412 #101]  INFO -- : [6190d2d9-eaa8-4ca8-a1f8-f8ec22cd2c08] Processing by HomeController#index as HTML                                                                                                              
I, [2019-11-10T22:03:20.269376 #101]  INFO -- : [6190d2d9-eaa8-4ca8-a1f8-f8ec22cd2c08]   Rendering home/index.html.haml within layouts/application                                                                                             
D, [2019-11-10T22:03:20.274184 #101] DEBUG -- : [6190d2d9-eaa8-4ca8-a1f8-f8ec22cd2c08]   Conference Exists (0.6ms)  SELECT  1 AS one FROM "conferences" LIMIT $1  [["LIMIT", 1]]                                                               
D, [2019-11-10T22:03:20.275392 #101] DEBUG -- : [6190d2d9-eaa8-4ca8-a1f8-f8ec22cd2c08]    (0.5ms)  SELECT COUNT(*) FROM "conferences" WHERE "conferences"."end_date" > '2019-11-10 21:03:20.267379'
D, [2019-11-10T22:03:20.278939 #101] DEBUG -- : [6190d2d9-eaa8-4ca8-a1f8-f8ec22cd2c08]   Conference Load (0.9ms)  SELECT  "conferences".* FROM "conferences" WHERE "conferences"."end_date" > '2019-11-10 21:03:20.267379' ORDER BY start_date DESC LIMIT $1 OFFSET $2  [["LIMIT", 10], ["OFFSET", 0]]
D, [2019-11-10T22:03:20.282251 #101] DEBUG -- : [6190d2d9-eaa8-4ca8-a1f8-f8ec22cd2c08]   CallForParticipation Load (0.6ms)  SELECT "call_for_participations".* FROM "call_for_participations" WHERE "call_for_participations"."conference_id" $ $1  [["conference_id", 1]]
I, [2019-11-10T22:03:20.285230 #101]  INFO -- : [6190d2d9-eaa8-4ca8-a1f8-f8ec22cd2c08]   Rendered home/_table.html.haml (8.0ms)
I, [2019-11-10T22:03:20.285354 #101]  INFO -- : [6190d2d9-eaa8-4ca8-a1f8-f8ec22cd2c08]   Rendered home/index.html.haml within layouts/application (15.9ms)
I, [2019-11-10T22:03:20.285598 #101]  INFO -- : [6190d2d9-eaa8-4ca8-a1f8-f8ec22cd2c08] Completed 500 Internal Server Error in 19ms (ActiveRecord: 2.6ms)
F, [2019-11-10T22:03:20.287925 #101] FATAL -- : [6190d2d9-eaa8-4ca8-a1f8-f8ec22cd2c08]   
F, [2019-11-10T22:03:20.287987 #101] FATAL -- : [6190d2d9-eaa8-4ca8-a1f8-f8ec22cd2c08] ActionView::Template::Error (undefined method `to_date' for nil:NilClass):
F, [2019-11-10T22:03:20.289591 #101] FATAL -- : [6190d2d9-eaa8-4ca8-a1f8-f8ec22cd2c08]     11:           - if conference.logo.present?
[6190d2d9-eaa8-4ca8-a1f8-f8ec22cd2c08]     12:             = image_box conference&.logo, :small
[6190d2d9-eaa8-4ca8-a1f8-f8ec22cd2c08]     13:         %td
[6190d2d9-eaa8-4ca8-a1f8-f8ec22cd2c08]     14:           = l(conference.start_date.to_date)
[6190d2d9-eaa8-4ca8-a1f8-f8ec22cd2c08]     15:           \- 
[6190d2d9-eaa8-4ca8-a1f8-f8ec22cd2c08]     16:           = l(conference.end_date.to_date)
[6190d2d9-eaa8-4ca8-a1f8-f8ec22cd2c08]     17:         %td= conference.title
F, [2019-11-10T22:03:20.289660 #101] FATAL -- : [6190d2d9-eaa8-4ca8-a1f8-f8ec22cd2c08]   
F, [2019-11-10T22:03:20.289693 #101] FATAL -- : [6190d2d9-eaa8-4ca8-a1f8-f8ec22cd2c08] app/views/home/_table.html.haml:14:in `block in _app_views_home__table_html_haml__2935257813225796309_47029699963920'
[6190d2d9-eaa8-4ca8-a1f8-f8ec22cd2c08] app/views/home/_table.html.haml:8:in `_app_views_home__table_html_haml__2935257813225796309_47029699963920'
[6190d2d9-eaa8-4ca8-a1f8-f8ec22cd2c08] app/views/home/index.html.haml:31:in `_app_views_home_index_html_haml___1013164915384176084_47029689876220'
```

**Comment by eladeyal-intel** [comment]
I think I was able to reproduce this by creating a conference with only title and acro and then browsing through the home screen. 

@pcfe Try to navigate to the url `/conference_acronym` and then go to settings -> days and add a day to see if this resolves the problem for you

**Comment by pcfe** [comment]
yes, even though the conference already had two days (both in the future), adding a third seems to have fixed the 500 errors on `/`

After that, I was able to delete the addtl day without ill effects.

**Comment by eladeyal-intel** [comment]
Maybe related to #620

**Comment by pcfe** [comment]
Sounds like it, but I do have that commit in the version I am using.
Will poke at this again one of the coming w-e.

**Comment by eladeyal-intel** [comment]
So there are two bugs here:

1. Import conference does not import the conference `start_date` and `end_date`.

2. `undefined method to_date for nil:NilClass` in the welcome screen if it tries to show a conference with `start_date` or `end_date` = null.

I fixed both in #648

**Comment by pcfe** [comment]
confirmed, after creating the two missing `.yaml` files, an older backup imported fine when #648 is included. (without the empty files I get the expected failure, but the fix for that can be just a two line documentation entry)

```bash
I have no name!@frab-123-5dgrf:~$ cp tmp/frab_export/event_links.yaml tmp/frab_export/conference_review_metrics.yaml
I have no name!@frab-123-5dgrf:~$ cp tmp/frab_export/event_links.yaml tmp/frab_export/event_review_scores.yaml
I have no name!@frab-123-5dgrf:~$ RAILS_ENV=production rake frab:conference_import --trace
** Invoke frab:conference_import (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute frab:conference_import
[ ] restore conference
    conference: DE Services Meeting Leipzig November 2019 (desm201911)
[ ] restore all conference_tracks
[ ] restore conference_cfp
[ ] restore conference_ticket_server
[ ] restore all conference_rooms
[ ] restore all conference_days
[ ] restore all conference_languages
[ ] restore all conference_review_metrics
[ ] restore all people
[ ] restore all users
[ ] restore all events
[ ] restore all tickets
[ ] restore all event_people
[ ] restore all event_feedbacks
[ ] restore all event_ratings
[ ] restore all event_review_scores
[ ] restore all event_links
[ ] restore all event_attachments
[ ] restore all people_phone_numbers
[ ] restore all people_im_accounts
[ ] restore all people_links
[ ] restore all people_languages
[ ] restore all people_availabilities
I have no name!@frab-123-5dgrf:~$ 
```

**Comment by eladeyal-intel** [comment]
I don't know if the export-import tasks are supposed to be backwards compatible. Not sure they can. One can do the restore using the old software version and then upgrade the software and migrate the database.

**Comment by pcfe** [comment]
I find creating two empty files absolutely acceptable, so far restoring an older backup has worked fine in my limited testing at home.

I agree that it's preferable to roll out the version the backup was made with and then restore followed by an upgrade, but being able to restore on a newer version is a nice bonus.

**Comment by eladeyal-intel** [comment]
Example: We changed the format of the the mail templates in #578 . I added a [migration](https://github.com/frab/frab/blob/master/db/migrate/20191004071111_update_mail_template_content.rb) to convert old templates to new templates; but the export/import will not do that.

Maybe we should write the schema version number to the export file and add a warning if importing from a non-current version.

**Comment by pcfe** [comment]
> Maybe we should write the schema version number to the export file and add a warning if importing from a non-current version.

yes please.
