### ISSUE TITLE
Not deployable on MySQL with existing DB

### ISSUE THREAD

**Issue by manno** [frab/frab#660]
Am I missing some setup to make this work?

```
Caused by:
Mysql2::Error: Cannot add foreign key constraint
/frab/shared/bundle/ruby/2.4.0/gems/mysql2-0.5.2/lib/mysql2/client.rb:131:in `_query'
/frab/shared/bundle/ruby/2.4.0/gems/mysql2-0.5.2/lib/mysql2/client.rb:131:in `block in query'
/frab/shared/bundle/ruby/2.4.0/gems/mysql2-0.5.2/lib/mysql2/client.rb:130:in `handle_interrupt'
/frab/shared/bundle/ruby/2.4.0/gems/mysql2-0.5.2/lib/mysql2/client.rb:130:in `query'
/frab/shared/bundle/ruby/2.4.0/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:187:in `block (2 levels) in execute'
/frab/shared/bundle/ruby/2.4.0/gems/activesupport-5.2.2.1/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
/frab/shared/bundle/ruby/2.4.0/gems/activesupport-5.2.2.1/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
/frab/shared/bundle/ruby/2.4.0/gems/activesupport-5.2.2.1/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
/frab/shared/bundle/ruby/2.4.0/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:186:in `block in execute'
/frab/shared/bundle/ruby/2.4.0/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/abstract_adapter.rb:579:in `block (2 levels) in log'
/frab/shared/bundle/ruby/2.4.0/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/abstract_adapter.rb:578:in `block in log'
/frab/shared/bundle/ruby/2.4.0/gems/activesupport-5.2.2.1/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
/frab/shared/bundle/ruby/2.4.0/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/abstract_adapter.rb:569:in `log'
/frab/shared/bundle/ruby/2.4.0/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:185:in `execute'
/frab/shared/bundle/ruby/2.4.0/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/mysql/database_statements.rb:28:in `execute'
/frab/shared/bundle/ruby/2.4.0/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/abstract/schema_statements.rb:311:in `create_table'
/frab/shared/bundle/ruby/2.4.0/gems/activerecord-5.2.2.1/lib/active_record/migration.rb:871:in `block in method_missing'
/frab/shared/bundle/ruby/2.4.0/gems/activerecord-5.2.2.1/lib/active_record/migration.rb:840:in `block in say_with_time'
/frab/shared/bundle/ruby/2.4.0/gems/activerecord-5.2.2.1/lib/active_record/migration.rb:840:in `say_with_time'
/frab/shared/bundle/ruby/2.4.0/gems/activerecord-5.2.2.1/lib/active_record/migration.rb:860:in `method_missing'
/frab/shared/bundle/ruby/2.4.0/gems/activerecord-5.2.2.1/lib/active_record/migration.rb:604:in `method_missing'
/frab/releases/20191120135825/db/migrate/20191004000001_create_review_metrics.rb:3:in `up'

```

**Comment by eladeyal-intel** [comment]
Was that a production DB? There should be more vebose explanation of failure.

My first guess would be the you used this DB to test one of my PRs; and since then I renamed the migrations so your DB would be inconsistent.

These migrations do work for mysql too.

![image](https://user-images.githubusercontent.com/20379005/69280027-3787f380-0bee-11ea-8e67-658abec482b2.png)


https://travis-ci.org/eladeyal-intel/frab/jobs/614740015?utm_medium=notification&utm_source=github_status

**Comment by eladeyal-intel** [comment]
Or maybe this has to do with the character encoding?

https://www.a2hosting.com/kb/developer-corner/mysql/convert-mysql-database-utf-8

**Comment by manno** [comment]
Rails 5.1 changed the primary key to `bigint`.

This solved it:

```
mysql> ALTER TABLE classifiers DROP FOREIGN KEY fk_rails_46;
mysql> ALTER TABLE classifiers MODIFY COLUMN conference_id bigint;
mysql> ALTER TABLE conferences MODIFY COLUMN id bigint auto_increment;
mysql> ALTER TABLE classifiers ADD CONSTRAINT fk_rails_46 FOREIGN KEY (conference_id) REFERENCES conferences(id);

mysql> alter table event_ratings modify column id bigint auto_increment;

mysql> ALTER TABLE event_classifiers DROP FOREIGN KEY fk_rails_4f;
mysql> ALTER TABLE event_classifiers MODIFY COLUMN event_id bigint;
mysql> ALTER TABLE events MODIFY COLUMN id bigint auto_increment;
mysql> ALTER TABLE event_classifiers ADD CONSTRAINT fk_rails_4f FOREIGN KEY (event_id) REFERENCES events(id);


```
